## REF: https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml
---
redis:
  architecture: standalone
  
  auth:
    enabled: false
  
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
    prometheusRule:
      enabled: false
  
  master:
    ## Add priority class name to ensure availability
    priorityClassName: high-priority

    ## NOTE: in bitnami charts the readiness, startup and liveness probes are set by default
    
    ## enable autoscaling (architecture: high-availability needed)
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 6
      targetCPU: 50
      targetMemory: 50
    
    ## Affinity and tolerations to enforce the deployment to specific nodes
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-type
              operator: In
              values:
              - data
    tolerations:
    - key: data
      value: dedicated
      operator: Equal
      effect: NoSchedule
  
  ## don't needed in standalone architecture 
  replica:
    replicaCount: 1
    ## Add priority class name to ensure availability
    priorityClassName: high-priority
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-type
              operator: In
              values:
              - data
    tolerations:
    - key: data
      value: dedicated
      operator: Equal
      effect: NoSchedule
