apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
# MetalLB native install
- https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml

patches:
## Patch priorityClassName in Deployments
- path: overlays/patch-priorityClassName-deployments.yaml
  target:
    kind: Deployment
- path: overlays/patch-tolerations-deployments.yaml
  target:
    kind: Deployment
## Patch priorityClassName in DaemonSets
- path: overlays/patch-priorityClassName-daemonsets.yaml
  target:
    kind: DaemonSet
- path: overlays/patch-tolerations-daemonsets.yaml
  target:
    kind: DaemonSet
