apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: minipokedex-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: minipokedex-api
  maxReplicas: 20
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
