apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minipokedex

commonLabels:
  environment: production

images:
- name: nginx
  newTag: "1.25.4"
- name: varbel/techtests
  newTag: v0.0.7-freepik-minipokedex-api-dev
- name: hipages/php-fpm_exporter
  newTag: "2.2.0"

resources:
- ../base
- hpa-minipokedex-api.yaml
- configmap-minipokedex-nginx-config.yaml
