apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-minipokedex-api
  labels:
    app.kubernetes.io/name: simple-minipokedex-api
    app.kubernetes.io/instance: simple-minipokedex-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-minipokedex-api
      app.kubernetes.io/instance: simple-minipokedex-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-minipokedex-api
        app.kubernetes.io/instance: simple-minipokedex-api
    spec:
      # imagePullSecrets:
      # - name: docker-registry-credentials
      containers:
      - name: application
        image: varbel/techtests:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9000
        envFrom:
        - secretRef:
            name: simple-minipokedex-api-env
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
