apiVersion: v1
kind: Service
metadata:
  name: simple-minipokedex-api
  labels:
    app.kubernetes.io/name: simple-minipokedex-api
    app.kubernetes.io/instance: simple-minipokedex-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: simple-minipokedex-api
    app.kubernetes.io/instance: simple-minipokedex-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
