# repository: https://github.com/kubernetes-sigs/kind
# docker hub: https://hub.docker.com/u/kindest
# kind config: https://kind.sigs.k8s.io/docs/user/configuration/
# kind ingress config: https://kind.sigs.k8s.io/docs/user/ingress
#
# nginx ingress controller: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
# kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=90s
# example: kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/usage.yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: freepik-cluster-config
#networking:
#  apiServerAddress: "127.0.0.1"
#  apiServerPort: 6443
#  podSubnet: "10.240.0.0/16"
#  serviceSubnet: "10.0.0.0/16"
#  disableDefaultCNI: true
nodes:
  ## master nodes
  ## https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/
  ## https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  
  ## general purpose nodes
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: general-purpose-01
          kubeletExtraArgs:
            node-labels: "node-type=general-purpose"
  
  ## worker nodes
  ## https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/
  ## data nodes
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: data-01
          kubeletExtraArgs:
            node-labels: "node-type=data"
          taints:
            - key: data
              value: dedicated
              operator: Equal
              effect: NoSchedule
  ## service nodes
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          name: service-01
          kubeletExtraArgs:
            node-labels: "node-type=service"
          taints:
            - key: service
              value: dedicated
              operator: Equal
              effect: NoSchedule
