apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minipokedex

resources:
## WARNING: use external secrets or similar solution in production environment
- secret-minipokedex-redis-credentials.yaml
