apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minipokedex

commonLabels:
  environment: production

images:
- name: nginx
  newTag: "1.25.4"
- name: varbel/techtests
  newTag: v0.0.2-freepik-minipokedex-api-dev

resources:
- ../base
- hpa-minipokedex-api.yaml
- configmap-minipokedex-nginx-config.yaml
