## REF: https://github.com/bitnami/charts/blob/main/bitnami/memcached/values.yaml
---
memcached:
  architecture: high-availability
  replicaCount: 1

  ## NOTE: in bitnami charts the readiness, startup and liveness probes are set by default

  ## Add priority class name to ensure availability
  priorityClassName: high-priority

  ## enable autoscaling (architecture: high-availability needed)
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 6
    targetCPU: 50
    targetMemory: 50
  
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
  
  ## Affinity and tolerations to enforce the deployment to specific nodes
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-type
            operator: In
            values:
            - data
  tolerations:
  - key: data
    value: dedicated
    operator: Equal
    effect: NoSchedule
