apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minipokedex

commonLabels:
  environment: production

resources:
- ingress-simple-minipokedex.yaml
- secret-simple-minipokedex-api-env.yaml
