apiVersion: v1
kind: Secret
metadata:
  name: simple-minipokedex-api-env
type: Opaque
stringData:
  ## WARNING: Use external secrets in production environment or add the values before deploy
  ## but you don't must store the core values in the git repository
  DDBB_HOST: "minipokedex-mariadb.minipokedex.svc.cluster.local"
  DDBB_PORT: "3306"
  DDBB_NAME: "minipokedex_data"
  DDBB_USER: "minipokedex"
  DDBB_PASS: "test123"
  DDBB_CHARSET: "utf8mb4"

  # Variables related to Redis
  REDIS_HOST: "minipokedex-redis-master.minipokedex.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_SCHEMA: "tcp"

  # Variables related to Memcached
  MEMCACHED_HOST: "minipokedex-memcached.minipokedex.svc.cluster.local"
  MEMCACHED_PORT: "11211"
