apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Ingress nginx kind install
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.0/deploy/static/provider/kind/deploy.yaml

patches:
## Patch priorityClassName in Deployments
- path: overlays/patch-priorityClassName-deployments.yaml
  target:
    kind: Deployment
- path: overlays/patch-tolerations-deployments.yaml
  target:
    kind: Deployment
