apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minipokedex

commonLabels:
  environment: production

resources:
- configmap-minipokedex-dashboard.yaml
- serviceMonitor-minipokedex-api.yaml
