apiVersion: v1
kind: Secret
metadata:
  name: secret-grafana-credentials
type: Opaque
stringData:
  # You can include additional key value pairs as you do with Opaque Secrets
  # WARNING: Add the grafana credentials in base64 before deploy
  username: admin
  password: test123
