## REF: https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
---
ingress-nginx:
  controller:
    # Mark the created ingressClass as the default in the cluster
    ingressClassResource:
      default: true

    # Resources for Ingress pods
    # Ideally, no limits needed
    resources:
      requests:
        cpu: 200m
        memory: 200Mi

    # Enable SSL connections directly to the services when requested on annotations
    extraArgs:
      enable-ssl-passthrough: "true"
    
    ## This in needed to set loadbalancer name
    service:
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-name: "freepik"
    
    tolerations:
    - effect: NoSchedule
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/disk-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/pid-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/unschedulable
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/network-unavailable
      operator: Exists
