apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minipokedex

commonLabels:
  environment: production

images:
- name: varbel/techtests
  newTag: v0.0.6-freepik-simple-minipokedex-api-dev

resources:
- ../base
- hpa-simple-minipokedex-api.yaml
