apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-prometheus-stack

resources:
# WARNING: This is a secret with sensitive information, this secret is only to develop environment, please
# use external secrets to generate this secret in production
- secret-alertmanagerconfig-secrets.yaml

# Deploy the template needed by Alertmanager to craft nice messages on Slack
- ConfigMap-alertmanager-templates.yaml

# Deploy the AlertmanagerConfig using the template
- AlertmanagerConfig-telegram-notifications.yaml

