apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

## REF: https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nginx-ingress-with-cert-manager-on-digitalocean-kubernetes
resources:
- clusterIssuer-production.yaml
- clusterIssuer-staging.yaml
- clusterIssuer-self-signed.yaml
# - secret-cloudflare-api-token.yaml
